### ISSUE TITLE
The demo pages are broken (CORS issue)

### ISSUE THREAD

**Issue by GuillaumeAmat** [teritorio/teritorio-map#23]
@frodrigo there is a CORS issue in the demo pages

**Comment by frodrigo** [comment]
An API key is now required.

**Comment by GuillaumeAmat** [comment]
Oh, I think we should remove the demos then. Or whitelist the github.io referrer?

**Comment by frodrigo** [comment]
I already whitelist, but it seam to not work.
I will fix this.

**Comment by GuillaumeAmat** [comment]
Great thanks
