### ISSUE TITLE
Add helper to disable POI superclass or class

### ISSUE THREAD

**Issue by frodrigo** [teritorio/teritorio-map#5]

**Comment by sbterito** [comment]
It should concern superclass, class, subclass. Can be used as a "preset" for the "whole" tile + others depending on the web context ("calls").

**Comment by sbterito** [comment]
An example (just a test, a part) will be very helpful for the meeting (22/05). _If possible, then, a test with the subclass restaurant would be great._  @frodrigo

**Comment by frodrigo** [comment]
PR https://github.com/teritorio/teritorio-map/pull/13
